server:
  port: 80

spring:
  application:
    name: api-gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: auth-service
          uri: ${AUTH} # http://localhost:9090/api/v1/auth/getpage
          predicates:
            - Path=/auth/**    # gelen isteği yakalar: http://localhost/auth/getpage
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - id: user-service
          uri:  ${USER}
          predicates:
             - Path=/userprofile/**    # gelen isteği yakalar: http://localhost/userprofile/getpage
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#          filters:
#            - RewritePath= /ahmetamca/?(?<segment>.*) , /api/v1/userprofile/$\{segment}
      default-filters:
        - RewritePath= /(?<segment>.*) , /api/v1/$\{segment}

